### ISSUE TITLE
Wilma list

### ISSUE THREAD

**Issue by ghost** [Wilma-Unofficial-API/parsing#2]
The list of wilma sites in https://starsoft.fi/wilmat/wilmat.json as shown in the wiki is not loading anymore. In fact, starsoft.fi itself is not loading anymore. I wonder if you have found another endpoint?

**Comment by NALStudio** [comment]
I've decompiled Wilma myself and the new endpoint seems to be "https://wilmahub.service.inschool.fi/wilmat"

_Just leaving it here if you need it... This repo seems a bit dead atm._

**Comment by developerfromjokela** [comment]
I've just updated new URL to wiki 👍
